---
- name: Add PHP repo
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
  - "php-bcmath"
  - "php-cli"
  - "php-common"
  - "php-curl"
  - "php-fpm"
  - "php-gd"
  - "php-igbinary"
  - "php-imagick"
  - "php-mbstring"
  - "php-mysql"
  - "php-opcache"
  - "php-redis"
  - "php-soap"
  - "php-xml"
  - "php-xmlrpc"
  - "php8-zip"

- name: Set PHP user
  lineinfile:
    dest: /etc/php//fpm/pool.d/www.conf
    regexp: "^user"
    line: "user = {{ username }}"
    state: present
  notify: restart php

- name: Set PHP group
  lineinfile:
    dest: /etc/php//fpm/pool.d/www.conf
    regexp: "^group"
    line: "group = {{ username }}"
    state: present
  notify: restart php

- name: Set PHP listen owner
  lineinfile:
    dest: /etc/php//fpm/pool.d/www.conf
    regexp: "^listen\\.owner"
    line: "listen.owner = {{ username }}"
    state: present
  notify: restart php

- name: Set PHP listen group
  lineinfile:
    dest: /etc/php//fpm/pool.d/www.conf
    regexp: "^listen\\.group"
    line: "listen.group = {{ username }}"
    state: present
  notify: restart php

- name: Set PHP upload max filesize
  lineinfile:
    dest: /etc/php//fpm/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 1024M"
    state: present
  notify: reload php

- name: Set PHP post max filesize
  lineinfile:
    dest: /etc/php//fpm/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 128M"
    state: present
  notify: reload php