---
- name: start php
  service:
    name: php7.2-fpm
    state: started

- name: reload php
  service:
    name: php7.2-fpm
    state: reloaded

- name: restart php
  service:
    name: php7.2-fpm
    state: restarted